apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-spring-boot.fullname" . }}-config
  labels:
    {{- include "common-spring-boot.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile | default "docker" | quote }}